name: This is first GitHub Action CI CD

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Show OS info
        run: cat /etc/os-release

      - name: Step 2 - Show current directory
        run: pwd

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Step 3 - adding deploy steps 
        run: echo "Deployment started at $(date +'%H:%M:%S')"