name: My CI CD

on: push

jobs:
  job_name:
    runs-on: ubuntu-latest
    steps:
      - name: first ci cd pipeline
        run: echo "Hello from github actions"

      - name: second steps
        run: echo "hello from second steps"


  jobname2:
    runs-on: ubuntu-latest 
    steps:
      - name: stepname 
        run: echo "hello from second JOB jobname2"