name: This is first GitHub Action CI CD

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Show OS info
        run: cat /etc/os-release

      - name: Step 2 - Show current directory
        run: pwd