name: github actions pipelines

on: push

jobs:
  vars:
    runs-on: ubuntu-latest
    steps:
      - name: Calling Var 1
        run: echo "${{vars.VAR_1}}"

      - name: login to docker hub
        run: echo "${{secrets.DOCKER_HUB_P}}"
