name: Artifacts Workflow
on: push

jobs:
  Installing-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install Dependences
        run: |
          python -m pip instakk --upgrade pip
          pip install -r requirements.txt
          
      - name: Running python script
        run: python my_script.py
