name: Self-Hosted Apache Install

on:
  push:

jobs:
  frequent_job:
    runs-on: self-hosted
    steps:
      - name: Update and install Apache
        run: |
          sudo apt update
          sudo apt install -y apache2
      - name: Check Apache status
        run: systemctl status apache2
