name: Atrifacts Workflow
on: push

jobs:
  creating_artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Creating artifacts
        run: echo "creating artifacts file names hello.txt" > hello.txt

      - name: Display File Contents
        run: cat hello.txt

      - name: Uploading artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hello-artifacts
          path: hello.txt

  downloading-artifacts:
    needs: creating_artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Adding Actions
        uses: actions/download-artifact@v4
        with:
          name: hello-artifacts
          
      - name: Reading File
        run: cat hello.txt
