name: Concurrency

on: push

concurrency:
  group: ci-${{github.ref}}
  cancel-in-progress: true

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - name: Concurrency Job
        run: |
          echo "Build"
