name: Artifacts Workflow
on: push

jobs:
  creating_artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Creating Dir
        run: mkdir creating-dir

      - name: Creating artifacts
        run: echo "creating artifacts file names hello.txt" > creating-dir/hello.txt

      - name: Display File Contents
        run: cat creating-dir/hello.txt

      - name: Uploading artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hello-artifacts
          path: creating-dir/  # upload directory

  downloading-artifacts:
    needs: creating_artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: hello-artifacts
          path: .  # extract directory to root

