name: Concurrency

on: push

concurrency:
  group: ci-${{github.ref}}
  cancel-in-progress: true

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - name: Concurrency Job
        run: |
          echo "Build"

      - name: adding if step
        if: success()
        run: echo "Build successfull"

      - name: Step 3 Always runs
        if: always()
        run: echo "This step always runs, success or failure."
