name: Artifacts Workflow
on: push

jobs:
  Installing-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: AwS
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-public-key: ${{secrets.AWS_PUBLIC_KEY}}
          aws-secret-key: ${{secrets.AWS_SECRET_KEY}}
          aws-region: ap-south-1

      - name: Verify AWS Identity
        run: aws sts get-caller-identity
