name: Artifacts Workflow
on: push

jobs:
  creating_artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0           # get full history
          persist-credentials: true
          submodules: recursive     # include submodules
          path: my-path/