name: Artifacts Workflow
on: push

jobs:
  Installing-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"  # safer, as 3.13 may not be fully supported

      - name: Create and run Python script
        run: |
          echo 'print("Hello from runner")' > script.py
          python script.py