name: Every 2 Minutes Workflow

on:
  schedule:
    - cron: "*/1 * * * *" # runs every 1 minutes automatically
  workflow_dispatch:

jobs:
  frequent_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print timestamp
        run: echo "Workflow triggered at $(date -u) UTC"
