name: Artifacts Workflow
on: push

jobs:
  Installing-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: List files
        run: ls -R

      - name: Run Python script
        run: python my_script.py